### ISSUE TITLE
Location is wrong

### ISSUE THREAD

**Issue by toncek345** [g14a/gitsee#4]
Maybe it's just a dummy data in development? :)

**Comment by g14a** [comment]
Are you able to see any value? Can you put a screenshot? @toncek345

**Comment by toncek345** [comment]
Sure, I'm not from Germany.

![image](https://user-images.githubusercontent.com/10179919/89890192-3e6af200-dbd3-11ea-9e5e-d06a087ca4c3.png)

**Comment by g14a** [comment]
Looking into it.

**Comment by g14a** [comment]
@toncek345 Did you change your location in the last 24 hours? Just asking, because my cache stores it for a period of 24 hours and then evicts it.

**Comment by toncek345** [comment]
Yes, my initial location was empty string.

**Comment by g14a** [comment]
Yes it is fixed now. Tell me if there's anything else wrong with it :)
